# Generated by Django 5.2.4 on 2025-08-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '物资类别',
                'verbose_name_plural': '物资类别',
                'db_table': 'MATERIAL_CATEGORY',
            },
        ),
    ]
