# Generated by Django 5.2.4 on 2025-08-15 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surcharge_type', models.CharField(max_length=50, verbose_name='加价类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='加价金额')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.materialcategory', verbose_name='物资类别')),
            ],
            options={
                'verbose_name': '加价规则',
                'verbose_name_plural': '加价规则',
                'db_table': 'SURCHARGE',
            },
        ),
    ]
