# Generated by Django 5.2.4 on 2025-08-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_surcharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Surcharge',
        ),
    ]
