# Generated by Django 5.2.4 on 2025-08-15 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
        ('region', '0001_initial'),
        ('specification', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '数据上传记录',
                'verbose_name_plural': '数据上传记录',
                'db_table': 'DATA_UPLOAD',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='地区')),
            ],
            options={
                'verbose_name': '项目映射',
                'verbose_name_plural': '项目映射',
                'db_table': 'PROJECT_MAPPING',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateField(verbose_name='到货日期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单价')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='下浮率')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='合计')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.materialcategory', verbose_name='物资类别')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specification.specification', verbose_name='规格')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='供应商')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='填报用户')),
                ('project_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmapping', verbose_name='项目映射')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'PROJECT',
                'ordering': ['-arrival_date'],
            },
        ),
    ]
