# Generated by Django 5.2.4 on 2025-08-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_anomaly',
            field=models.BooleanField(default=False, verbose_name='是否异常'),
        ),
    ]
