# Generated by Django 5.2.4 on 2025-08-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='区/县')),
                ('citypy', models.CharField(blank=True, max_length=50, null=True, verbose_name='市拼音')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 'REGION',
                'unique_together': {('city', 'district')},
            },
        ),
    ]
