# Generated by Django 5.2.4 on 2025-08-15 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcretePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('wuhan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='武汉市')),
                ('huanggang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='黄冈市')),
                ('xiangyang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='襄阳市')),
                ('shiyan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='十堰市')),
                ('jingzhou', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='荆州市')),
                ('yichang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宜昌市')),
                ('enshi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='恩施市')),
                ('suizhou', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='随州市')),
                ('jingmen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='荆门市')),
                ('ezhou', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='鄂州市')),
                ('xiantao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='仙桃市')),
                ('qianjiang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='潜江市')),
                ('tianmen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='天门市')),
                ('shennongjia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='神农架')),
                ('xianning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='咸宁市')),
                ('huangshi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='黄石市')),
                ('xiaogan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='孝感市')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '混凝土信息价',
                'verbose_name_plural': '混凝土信息价',
                'db_table': 'CONCRETE_PRICE',
                'ordering': ['-date'],
            },
        ),
    ]
