# Generated by Django 5.2.4 on 2025-08-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100, unique=True, verbose_name='品牌名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='品牌描述')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'BRAND',
            },
        ),
        migrations.CreateModel(
            name='ConcretePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('wuhan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='武汉市')),
                ('huanggang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='黄冈市')),
                ('xiangyang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='襄阳市')),
                ('shiyan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='十堰市')),
                ('jingzhou', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='荆州市')),
                ('yichang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宜昌市')),
                ('enshi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='恩施市')),
                ('suizhou', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='随州市')),
                ('jingmen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='荆门市')),
                ('ezhou', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='鄂州市')),
                ('xiantao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='仙桃市')),
                ('qianjiang', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='潜江市')),
                ('tianmen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='天门市')),
                ('shennongjia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='神农架')),
                ('xianning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='咸宁市')),
                ('huangshi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='黄石市')),
                ('xiaogan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='孝感市')),
            ],
            options={
                'verbose_name': '混凝土信息价',
                'verbose_name_plural': '混凝土信息价',
                'db_table': 'CONCRETE_PRICE',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='区/县')),
                ('citypy', models.CharField(blank=True, max_length=50, null=True, verbose_name='市拼音')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 'REGION',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200, unique=True, verbose_name='供应商名称')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'SUPPLIER',
            },
        ),
    ]
