# Generated by Django 5.2.4 on 2025-08-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteprice',
            name='huangshi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='黄石市'),
        ),
        migrations.AddField(
            model_name='concreteprice',
            name='xianning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='咸宁市'),
        ),
        migrations.AddField(
            model_name='concreteprice',
            name='xiaogan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='孝感市'),
        ),
    ]
