# Generated by Django 5.2.4 on 2025-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_concreteprice_huangshi_concreteprice_xianning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='citypy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市拼音'),
        ),
    ]
