# Generated by Django 5.2.4 on 2025-08-15 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specification_name', models.CharField(max_length=200, verbose_name='规格名称')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.materialcategory', verbose_name='物资类别')),
            ],
            options={
                'verbose_name': '规格',
                'verbose_name_plural': '规格',
                'db_table': 'SPECIFICATION',
                'unique_together': {('category', 'specification_name')},
            },
        ),
    ]
