# Generated by Django 5.2.4 on 2025-08-14 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_region_citypy'),
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='projectmapping',
            name='city',
        ),
        migrations.RemoveField(
            model_name='projectmapping',
            name='district',
        ),
        migrations.AddField(
            model_name='project',
            name='project_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visual.projectmapping', verbose_name='项目映射'),
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.region', verbose_name='地区'),
        ),
    ]
