# Generated by Django 5.2.4 on 2025-08-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_region_citypy'),
        ('visual', '0002_remove_project_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_mapping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visual.projectmapping', verbose_name='项目映射'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.region', verbose_name='地区'),
            preserve_default=False,
        ),
    ]
