# Generated by Django 5.2.4 on 2025-08-14 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_supplier'),
        ('visual', '0003_alter_project_project_mapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.supplier', verbose_name='供应商'),
        ),
    ]
